/*
Find the n’th term in Look-and-say (Or Count and Say) Sequence. 
The look-and-say sequence is the sequence of the below integers: 
1, 11, 21, 1211, 111221, 312211, 13112221, 1113213211, … 

How is the above sequence generated? 
n’th term is generated by reading (n-1)’th term.

The first term is "1"

Second term is "11", generated by reading first term as "One 1" 
(There is one 1 in previous term)

Third term is "21", generated by reading second term as "Two 1"

Fourth term is "1211", generated by reading third term as "One 2 One 1" 

and so on

Input: n = 3
Output: 21

Input: n = 5
Output: 111221

Question Link: https://www.codingninjas.com/codestudio/problems/look-say-sequence_668478?topList=top-recursion-and-backtracking-interview-questions
*/
#include<string>
#include<iostream>
using namespace std;
string lookAndSaySequence(int n) 
{
    // Write your code here.
    if(n == 1){
        return "1";
    }
    string ans = lookAndSaySequence(n-1);
    string output = "";
    int count = 0;
    char item = ans[0];
    for(int i = 0; i < ans.size(); i++){
        if(ans[i] == item){
            count++;
        }
        else{
            char charcount = '0' + count;
            output = output + charcount + ans[i-1];
            count = 1;
            item = ans[i];

        }
    }
    char charcount = '0' + count;
    output = output + charcount + ans[ans.size()-1];
    return output;

}

int main()
{
    int n = 6;
    cout << lookAndSaySequence(n) << endl;
    return 0;
}
