/*
Given a string, we have to find out all its subsequences of it. 
A String is a subsequence of a given String, that is generated by deleting 
some character of a given string without changing its order.


Input : abc
Output : a, b, c, ab, bc, ac, abc

Input : aaa
Output : a, a, a, aa, aa, aa, aaa

Question Link: https://www.codingninjas.com/codestudio/problems/subsequences-of-string_985087
*/ 


#include<iostream>
#include<vector>
#include<string>
using namespace std;

void getSubsequence(string s, vector<string> &outputs, int n, int start, string ans){

    
    if(n == 1){
        outputs.push_back(ans);
        outputs.push_back(ans + s[start]);
        return;
    }
    getSubsequence(s, outputs, n - 1, start + 1, ans);
    ans = ans + s[start];
    getSubsequence(s, outputs, n - 1, start + 1, ans);
    return;
}
void print(vector<string> vec){
    for (int i = 0; i < vec.size(); i++){
        cout << vec[i] << endl;
    }
}
int main()
{
    string s = "abc";
    int n = s.size();
    int start = 0;
    string ans = "";
    vector<string> outputs;
    getSubsequence(s, outputs, n, start, ans);
    print(outputs);
    return 0;
}
